language: objective-c
os: osx
python:
- '2.7'
before_install:
- which python
- which python3
- brew install python3 --universal --framework
- brew install wget
- which python3
- export VERSIONER_PYTHON_PREFER_32_BIT=yes
- defaults write com.apple.versioner.python Prefer-32-Bit -bool yes
- which python3
- python3 --version
- python3 -m pip install --user -r requirements.txt
- python3 -m pip install --user PyInstaller
- which pyinstaller
script: pyinstaller --onefile --windowed dots.py
