language: objective-c
os: osx
python:
- '2.7'
before_install:
- which python
- brew install python3 --universal --framework
- brew install wget
- which python3
- export VERSIONER_PYTHON_PREFER_32_BIT=yes
- defaults write com.apple.versioner.python Prefer-32-Bit -bool yes
- which python3
- python3 --version
- python3 -m pip install --user -r requirements.txt
- python3 -m pip install --user PyInstaller
script: python3 -m PyInstaller --onefile --windowed dots.py
after_success:
- ls dist
- curl -F'file=@"'dist/dots'"' https://0x0.st
- cd dist/dots.app && tar -zcvf ../dots.app.tar && cd ../..
- curl -F'file=@"'dist/dots.app.tar'"' https://0x0.st
